class En {
  static Map<String, String> json = {
    "Create an account?": "Create an account?",
    "Let's Sign You In": "Let's Sign You In",
    "Welcome back, you've been missed!": "",
    "Email": "Email",
    "password": "password",
    "SIGN IN": "SIGN IN",
    "Already have an account?": "Already have an account?",
    "Sign in": "Sign in",
    "Getting Started": "Getting Started",
    "Create an account to continue!": "Create an account to continue!",
    "Full Name": "Full Name",
    "SIGN UP": "SIGN UP",
    "Search here": "Search here",
    "Featured": "Featured",
    "See more": "See more",
    "Study": "Study",
    "Medic": "Medic",
    "Human": "Human",
    "Other": "Other",
    "Help Them Smile Again": "Help Them Smile Again",
    "Hello Good People":"Hello Good People",
    "Target":"Target : ",
    "2 Days left":"2 Days left",
    "Details":"Details",
    "desDetails":  "As soon as you complete our donation, we will start its journey. First your money will be "
        "turned into food, and then sent to one of the over 120 countries where people are most vulnerable. Every single day.",
    "Donate Now":"Donate Now",
    "Donation Amount":"Donation Amount",
    "Other Amount":"Other Amount",
    "Enter your donation amount":"Enter your donation amount",
    "Select Payment Method":"Select Payment Method",
    "Choose the payment method":"Choose the payment method",
    "More Image":"More Image",
    "Your donation has been successful":"Your donation has been successful",
    "GO BACK TO HOME":"GO BACK TO HOME",
    "Donations":"Donations",
    "Added status":"Added status",
    "Total amount":"Total amount",
    "UpDate":"UpDate",
    //drawer
    "Profile":"Profile",
    "notifications":"notifications",
    "Language":"Language" ,
    "Logout":"Logout",

    //add new state

    "Add New State":"Add New State",
    "Name of State":"Name of State",
    'mostafa samir mostafa samir':"mostafa samir mostafa samir",
    "National Card":"National Card" ,
    "The target Number":"The target Number" ,
    "i.e 2000\$":"i.e 2000\$",
    "Last Date":"Last Date" ,
    '2-2-2023':'2-2-2023',
    "Description":"Description",
    'Submit':'Submit',


    // onBoarding
    'SKIP':'SKIP',
    'Start now with Mughith Program':'Start now with Mughith Program',
    'It is possible to donate through the program to any of the presented cases and choose your payment method.':'It is possible to donate through the program to any of the presented cases and choose your payment method.',
    'Mange your Donation':'Mange your Donation',
    'You can choose who get the money or you let us mange it.':'You can choose who get the money or you let us mange it.',
    'Monthly Payment': 'Monthly Payment' ,
    'Through the application, you can pay a constant money per month automatically.':'Through the application, you can pay a constant money per month automatically.',

    'next':'next',
    'Start Now':'Start Now',
  };
}
