class En {
  static Map<String, String> json = {
    "Password": "Password",
    "Email or phone number": "Email or phone number",
    "Sign In": "Sign In",
    "Forget Password?": "Forget Password?",
    "  Welcome Back 👋": "  Welcome Back 👋",
    "Invaild Data": "Invaild Data",
    "or continue with": "or continue with",
    "Please enter all data, enter all fields":
        "Please enter all data, enter all fields",
    "Please log in to your account": "Please log in to your account",
    "we provide the best learning courses & great mentors":
        "we  provide the best learning courses & great mentors",
    "learn anytime &anywhere easily and conveniently":
        "learn anytime &anywhere easily and conveniently",
    "NEXT": "NEXT",
    "Get Start": "Get Start",
    "Best Seller": "Best Seller",
    "Student": "Student",
    "Overview": "Overview",
    "Units": "Units",
    "Resources": "Resources",
    "Home": "Home",
    "My Courses": "My Courses",
    "Search": "Search",
    "Profile": "Profile",
    "Courses": "Courses",
    "Good Morning": "Welcome",
    "EGB": "EGB",
    "By ": "By ",
    "Completed": "Completed",
    "Ongoing": "Ongoing",
    "Details": "Details",
    "Choose your language": "Choose your language",
    "Account": "Account",
    "Edit Profile": "Edit Profile",
    "Change Password": "Change Password",
    "Social connect": "Social connect",
    "Nationality": "Nationality",
    "Support": "Support",
    "Contact Support": "Contact Support",
    "Privacy": "Privacy",
    "Terms of services": "Terms of services",
    "Other": "Other",
    "Language": "Language",
    "Log out": "Log out",
    " min": " min",
    "Please login to your account": "Please login to your account",
    "Go To Login": "Go To Login",
    "Please Wait...": "Please Wait...",
    "Loading": "Loading",
    "Top Courses": "Top Courses",
    "Top WorkShop": "Top WorkShop",
    "Phone Number": "Phone Number",
    "Email Address": "Email Address",
    "Full Name": "Full Name",
    "HERE": "HERE",
    "Login to your account from": "Login to your account from",
    "Create account from": "Create account from",
    "Don't have an account": "Don't have an account ?",
    "Already have an account": "Already have an account ?",
    "Register": "Register",
    "Theme": "Theme",
    "Are You Sure ?": "Are You Sure ?",
    "Light": "Light",
    "Dark": "Dark",
    "Yes": "Yes",
    "No": "No",
    "Last Name": "Last Name",
    "Choose your Theme": "Choose your Theme",
    "Login": "Login",
    "You do not have access to this course":
        "You do not have access to this course",
    "This course is not among the courses that I joined":
        "This course is not among the courses that I joined",
    "hour": "hour ",
    "No Data Found": "No Data Found",
    "Questions": "Questions",
    "There are no videos available": "There are no videos available",
    "Delete My Account": "Delete My Account",
    "Enter your reply": "Enter your reply",
    "Public Questions": "Public Questions",
    "Edit Question": "Edit Question",
    "Delete Question": "Delete Question",
    "reply": "reply",
    "My Questions": "My Questions",
    "Enter your question": "Enter your question",
    "Buy this course": "Buy this course",
    "Total": "Total",
    "Pay Now": "Pay Now",
    "Price": "Price"
  };
}
